CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(128) NOT NULL,
    content TEXT NOT NULL,
    remind_time TIMESTAMP NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_time TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tasks_user_id ON tasks (user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_due ON tasks (status, remind_time);
